{% set version = "1.8.0" %}

package:
  name: numpydoc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/numpydoc/numpydoc-{{ version }}.tar.gz
  sha256: 022390ab7464a44f8737f79f8b31ce1d3cfa4b4af79ccaa1aac5e8368db587fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - numpydoc = numpydoc.cli:main

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=61.2
  run:
    - python >=3.9
    - sphinx >=6
    - tabulate >=0.8.10
    - tomli >=1.1.0

test:
  requires:
    - pip
  imports:
    - numpydoc
  commands:
    - pip check
    - python -m numpydoc --help
    - numpydoc --help

about:
  home: https://github.com/numpy/numpydoc
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Numpy's Sphinx extensions
  doc_url: https://numpydoc.readthedocs.io

extra:
  recipe-maintainers:
    - jschueller
    - scopatz
    - bollwyvl
