# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.10.0"

package:
  name: numpydoc
  version: ${{ version }}

source:
  #url: https://pypi.org/packages/source/n/numpydoc/numpydoc-${{ version }}.tar.gz
  #sha256: 3f7970f6eee30912260a6b31ac72bba2432830cd6722569ec17ee8d3ef5ffa01
  url: https://github.com/numpy/numpydoc/archive/v1.10.0.tar.gz
  sha256: 7005b3902c764dbb5d5a79889727d7aef39896c48f6b1ec252c2741d83140221

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - numpydoc = numpydoc.cli:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61.2
  run:
    - python >=${{ python_min }}
    - sphinx >=6
    - tomli >=1.1.0

tests:
  - python:
      imports: numpydoc
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - python -m numpydoc --help
      - numpydoc --help
  - requirements:
      run:
        - matplotlib-base
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - coverage run --source=numpydoc --branch -m pytest -vv --tb=long --color=yes --pyargs numpydoc -k "not (test_main and test_lint)"
      - coverage report --show-missing --skip-covered --fail-under=84

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: "Numpy's Sphinx extensions"
  homepage: https://github.com/numpy/numpydoc
  documentation: https://numpydoc.readthedocs.io

extra:
  recipe-maintainers:
    - jschueller
    - scopatz
    - bollwyvl
